#!/bin/bash

if [ "$1" == "" ]; then
    echo "Missing component name"
	exit 0
fi

if [ ! -d ./$1 ]; then
	echo -e "Creating $1/$1.js"
	echo -e "Creating $1/$1.css"
	echo -e "Creating $1/index.js"
fi

mkdir $1
touch $1/$1.css
touch $1/$1.js
touch $1/index.js

class=$"import React, { Component } from 'react'
import './$1.css'

const $1 = () =>

export default $1"

index=$"export default from './$1'"

echo "$class" > $1/$1.js
echo "$index" > $1/index.js
